from .attr import attr_coherence_test 
from .label import label_coherence_test 
from .attr_dist import attr_dist_coherence_test 
from .random_dist import random_dist_coherence_test 
from .label_dist import label_dist_coherence_test 
from .has_link import has_link_coherence_test 
from .common_neighbor import common_neighbor_coherence_test
from .degree_dist import degree_dist_coherence_test
from .graph_distance import graph_distance_coherence_test
from .pagerank import pagerank_coherence_test
